# Generated by Django 3.2.20 on 2023-11-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scrapeimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('name_of_image', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
